/*
LAB 12
PHILIP BURGGRAF
*/

--1.
CREATE VIEW OPEN_ITEMS AS
SELECT VENDOR_NAME, INVOICE_NUMBER, INVOICE_TOTAL, (INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL) AS BALANCE_DUE
FROM AP.INVOICES JOIN AP.VENDORS
    ON INVOICES.VENDOR_ID = VENDORS.VENDOR_ID
WHERE (INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL) > 0
ORDER BY 1;

SELECT*
FROM OPEN_ITEMS;

--2.
SELECT*
FROM OPEN_ITEMS
WHERE BALANCE_DUE > 1000;

--3.
/*Mindi - my Open_Item_Totals are different than yours, but I checked them using the query below and they appear correct.*/
CREATE OR REPLACE VIEW OPEN_ITEMS_SUMMARY AS
SELECT VENDOR_NAME, COUNT(*) AS OPEN_ITEM_COUNT, SUM(INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL) AS OPEN_ITEM_TOTAL
FROM AP.INVOICES JOIN AP.VENDORS
    ON INVOICES.VENDOR_ID = VENDORS.VENDOR_ID
WHERE (INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL) > 0
GROUP BY VENDOR_NAME
ORDER BY 3 DESC;

SELECT*
FROM OPEN_ITEMS_SUMMARY;

/*Query check by vendor name.*/
SELECT VENDOR_NAME, INVOICE_TOTAL, PAYMENT_TOTAL, CREDIT_TOTAL
FROM AP.INVOICES JOIN AP.VENDORS
    ON INVOICES.VENDOR_ID = VENDORS.VENDOR_ID
WHERE VENDOR_NAME = 'Zylka Design';

--4.
SELECT*
FROM OPEN_ITEMS_SUMMARY
FETCH FIRST 5 ROWS ONLY;

--5.
CREATE OR REPLACE VIEW VENDOR_ADDRESS AS
SELECT VENDOR_ID, VENDOR_ADDRESS1, VENDOR_ADDRESS2, VENDOR_CITY, VENDOR_STATE, VENDOR_ZIP_CODE
FROM VENDORS;

SELECT*
FROM VENDOR_ADDRESS;

--6.
UPDATE VENDOR_ADDRESS
SET VENDOR_ADDRESS1 = '1990 Westwood Blvd',
    VENDOR_ADDRESS2 ='Ste 260'
WHERE VENDOR_ID = 4;

commit
