/*
Philip Burggraf
Lab - 8
*/

--1.
SELECT DISTINCT COST
FROM STUDENT.COURSE
WHERE COST =
    (SELECT MIN(COST)
    FROM STUDENT.COURSE);

--2. HELP
SELECT DISTINCT COST
FROM STUDENT.COURSE
WHERE COST IS NOT NULL;

SELECT COST
FROM STUDENT.COURSE
WHERE COST NOT IN
    (SELECT COST
    FROM STUDENT.COURSE
    WHERE COST BETWEEN MIN(COST) AND MAX(COST));

SELECT COST
FROM STUDENT.COURSE
WHERE COST NOT IN;
    (SELECT COST
    FROM STUDENT.COURSE
    WHERE COST BETWEEN MIN(COST) AND MAX(COST)
(SELECT COST
FROM STUDENT.COURSE));

--3.
SELECT COST
FROM STUDENT.COURSE
WHERE COST >
    (SELECT AVG(COST)
    FROM STUDENT.COURSE);

--4.
SELECT MIN(ENROLL_DATE) AS "Earliest Enrollment Date"
FROM STUDENT.ENROLLMENT;

--5.
SELECT MIN(ENROLL_DATE) + 30 AS "Earliest Date Plus 30"
FROM STUDENT.ENROLLMENT;

--6.
SELECT v.VENDOR_NAME, i.INVOICE_NUMBER, i.INVOICE_TOTAL
FROM AP.VENDORS v JOIN AP.INVOICES i
ON v.VENDOR_ID = i.VENDOR_ID
WHERE i.INVOICE_TOTAL <
    (SELECT MAX(invoice_total)
    FROM AP.VENDORS v2 JOIN AP.INVOICES i2
    ON v2.VENDOR_ID = i2.VENDOR_ID
    WHERE v2.VENDOR_ID = '123')
ORDER BY VENDOR_NAME, INVOICE_TOTAL DESC;

--7.
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_STATE
FROM AP.VENDORS
WHERE VENDOR_ID NOT IN
    (SELECT DISTINCT VENDOR_ID
    FROM AP.INVOICES)
ORDER BY VENDOR_ID;

--8.
SELECT LAST_NAME, FIRST_NAME
FROM STUDENT.STUDENT
WHERE LAST_NAME LIKE '&A%' AND FIRST_NAME LIKE '&B%'
ORDER BY LAST_NAME;

--9.
SELECT COST
FROM STUDENT.COURSE
WHERE COST >
    (SELECT MIN(COST)
    FROM STUDENT.COURSE);

--10.
SELECT VENDOR_ID, INVOICE_NUMBER, INVOICE_TOTAL
FROM AP.INVOICES inv_main
WHERE invoice_total >
    (SELECT AVG(INVOICE_TOTAL)
    FROM AP.INVOICES inv_sub
    WHERE inv_sub.vendor_id = inv_main.vendor_id)
ORDER BY VENDOR_ID, INVOICE_TOTAL;

--11.
SELECT v.VENDOR_ID, VENDOR_NAME, INVOICE_ID
FROM AP.VENDORS v JOIN AP.INVOICES i
    ON v.VENDOR_ID = i.VENDOR_ID
ORDER BY VENDOR_NAME;

--12.
SELECT VENDOR_NAME, COUNT(INVOICE_ID)
FROM AP.INVOICES i JOIN AP.VENDORS v
    ON i.VENDOR_ID = v.VENDOR_ID
GROUP BY VENDOR_NAME
ORDER BY VENDOR_NAME;

--13.
SELECT VENDOR_CONTACT_LAST_NAME, VENDOR_CONTACT_FIRST_NAME, VENDOR_STATE
FROM AP.VENDORS
WHERE (LENGTH(VENDOR_CONTACT_LAST_NAME) > LENGTH(VENDOR_CONTACT_FIRST_NAME)) AND (VENDOR_STATE = 'CA' OR VENDOR_STATE = 'NJ')
ORDER BY VENDOR_CONTACT_LAST_NAME;

--14.
SELECT VENDOR_ID, VENDOR_NAME
FROM AP.VENDORS
WHERE INSTR(VENDOR_NAME,'''') > 0;

--15. Subquery returns vendors with a space in there name, but initialy query causes it to return zero rows
SELECT VENDOR_NAME
FROM AP.VENDORS
WHERE VENDOR_NAME NOT IN
    (SELECT VENDOR_NAME
    FROM AP.VENDORS
    WHERE REGEXP_SUBSTR(VENDOR_NAME,' ', 1, 1, 'x') IS NULL);