/*LAB 4
PHILIP BURGGRAF*/

--1. 
SELECT TO_CHAR(INVOICE_TOTAL, '$99,999.99')
FROM AP.INVOICES
WHERE ROWNUM <=10;

--2.
SELECT TO_CHAR(INVOICE_TOTAL, '9.99EEEE')
FROM AP.INVOICES
WHERE ROWNUM <=10;

--3.
SELECT *
FROM
    (SELECT TO_CHAR(INVOICE_DATE, 'MM/DD/YYYY')
    FROM AP.INVOICES
    ORDER BY INVOICE_DATE)
WHERE ROWNUM <=10;

--4.
SELECT *
FROM AP.INVOICES
WHERE TRUNC(INVOICE_DATE) = '07-MAY-2014';

--5.
SELECT *
FROM STUDENT.ENROLLMENT
WHERE TRUNC(ENROLL_DATE) = '30-JAN-2007';

--6.
SELECT *
FROM
    (SELECT CONCAT(CONCAT(CONCAT(CONCAT(CITY, ', '), STATE), ' '), ZIP) AS "ALL TOGETHER WITH CONCAT"
    FROM STUDENT.ZIPCODE
    ORDER BY CITY)
WHERE ROWNUM <= 10;

--7. 
SELECT * 
FROM 
    (SELECT CITY || ', ' || STATE || ' ' || ZIP AS "ALL TOGETHER WITH ||"
    FROM STUDENT.ZIPCODE
    ORDER BY CITY)
WHERE ROWNUM <= 10;

--8.
SELECT *
FROM
    (SELECT CITY, UPPER(CITY) AS "Upper", LOWER(CITY) AS "Lower", INITCAP(CITY) AS "Mixed"
    FROM STUDENT.ZIPCODE
    ORDER BY CITY)    
WHERE ROWNUM <= 10;

--9. 
SELECT *
FROM
    (SELECT CITY
    FROM STUDENT.ZIPCODE
    WHERE LENGTH(CITY) >= 5 AND LENGTH(CITY) <= 9
    ORDER BY CITY)
WHERE ROWNUM <= 10;

--10.
SELECT * 
FROM 
    (SELECT CITY, SUBSTR(CITY, 2, 3)
    FROM STUDENT.ZIPCODE
    ORDER BY CITY)
WHERE ROWNUM <= 10;

--11.
SELECT * 
FROM 
    (SELECT CITY, SUBSTR(CITY, -3)
    FROM STUDENT.ZIPCODE
    ORDER BY CITY)
WHERE ROWNUM <= 10;

--12.
SELECT STUDENT_ID, NVL(MIDTERM_GRADE, 0) AS "NO GRADE FOUND", FINALEXAM_GRADE, QUIZ_GRADE
FROM STUDENT.GRADE_SUMMARY;

--13.
SELECT STUDENT_ID, SALUTATION, 'Doctor' AS "New Salutation"
FROM STUDENT.STUDENT
WHERE SALUTATION = 'Dr.';

--14.
SELECT *
FROM
    (SELECT STREET_ADDRESS, RTRIM(STREET_ADDRESS) AS "TRIMMED ADDRESS"
    FROM STUDENT.STUDENT
    ORDER BY STREET_ADDRESS)
WHERE ROWNUM <= 10;

--15.
SELECT TO_NUMBER(122.04) AS "STRING TO NUMBER"
FROM DUAL;

--16.
SELECT SQRT(4) AS "SQRT OF 4", SQRT(0) AS "SQRT OF 0"
FROM DUAL;
    
    
