/*
PL 15
Philip Burggraf
*/

--1.
CREATE OR REPLACE TRIGGER Lab15Trigger1
AFTER DELETE
ON EMPLOYEE_COPY_PL15
BEGIN
INSERT INTO EMPLOYEE_COPY_PL15
(EMPLOYEE_ID, NAME, SALARY, TITLE)
VALUES (5,'Philip', 100000, 'CEO');
END;

--2.
ALTER TRIGGER Lab15Trigger1 DISABLE;

--3.
CREATE OR REPLACE TRIGGER LAB15TRIGGER2
BEFORE DELETE ON EMPLOYEE_COPY_PL15
DECLARE 
count_value NUMBER;
BEGIN
SELECT COUNT(*)
INTO count_value
FROM EMPLOYEE_COPY_PL15;

IF count_value < 20 THEN
RAISE_APPLICATION_ERROR(-20101, 'At least 20 rows must be in the employee_copy table');
END IF;
END;



